function fetchUserData(url) {
    // Return the Promise generated by fetch()
    return fetch(url)
        .then((response) => response.json())
        .then((data) => {
            console.log(data);
            return data; // Return the fetched data
        })
        .catch((error) => {
            console.log(error);
        });
}

async function getUserData() {
    // Call fetchUserData() and log user data to console using async/await syntax
    let data = await fetchUserData("https://jsonplaceholder.typicode.com/users/1");
    console.log(data);
}

getUserData();

function getUserAge() {
    // Return the Promise generated by fetchUserData()
    return fetchUserData("https://jsonplaceholder.typicode.com/users/1")
        .then((response) => response.json())
        .then((data) => {
            console.log(data);
            return data.age; // Return the user age
        });
}

async function getAgeAndLog() {
    // Call getUserAge() and log user age to console using async/await syntax
    let age = await getUserAge();
    console.log(age);
}

getAgeAndLog();
